name: Trigger Close CircleCI Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
