name: Created Comment

on:
  issue_comment:
    types: [created]

jobs:
  checkout:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/preview')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Echo ref
        run: echo $GITHUB_REF
      - name: Trigger
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.6
        with:
          GHA_Meta: 'preview'
        env:
          CCI_TOKEN: 04174f2c87bf4f652e60a485bc62022d2a37c6a6
    
    
    
    