name: Created Comment

on:
  issue_comment:
    types: [created]

jobs:
  checkout:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/preview')
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - run: git rev-parse --abbrev-ref HEAD
      - run: git rev-parse --verify HEAD
      - name: Echo ref
        run: echo $GITHUB_REF
      - name: Trigger
        uses: tommy-anderson/trigger-circleci-pipeline-action@v2.1
        with:
          GHA_Meta: 'preview'
          GHA_Branch: ${{ steps.comment-branch.outputs.head_ref }}
        env:
          CCI_TOKEN: 04174f2c87bf4f652e60a485bc62022d2a37c6a6
    
    
    
    