name: Created Comment

on:
  issue_comment:
    types: [created]

jobs:
  checkout:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/preview')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
    