name: Preview Check
on:
  pull_request:
    types: [labeled]
jobs:
  preview-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if preview label exists
        if: github.event.label.name == 'preview'
        run: echo PR was labeled with preview
